began updating with options

diff --git a/codes/leaf_loop b/codes/leaf_loop
--- a/codes/leaf_loop
+++ b/codes/leaf_loop
@@ -1,9 +1,62 @@
 #!/bin/bash
 set -e
-#Bamlocation=$1
-LeafcutterLoc=$1 #required option
-out=$2 #update as option - the prefix you wish the counts.gz files to have
+
+LeafcutterLocDefault=~/leafcutter/
+MinimumClusteringDefault=30
+LengthMaximumDefault=100000
+RatioMinimumDefault=0.001
+OutputDirectoryDefault=~/leaf_out/
+PCDefault=10
+OutputPrefixPrefixDefault=leafcutter
+
+#also needs an input option default can be set to the fastq_list_star.txt generated by star
+#update -m, 
+#-l, and 
+#-o as options - also add 
+#-r -> -w
+#-p -> -r
+#add -p option note that this option is different from the -p option from clustering
+
+while :
+do
+    case "$1" in
+
+      -l | --lengthmaximum) #maximum length of introns to be used in clustering
+      	  LengthMaximum="$2"
+	  shift 2
+	  ;;
+      -o | --outputprefix) #prefix of intron
+      	  OutputPrefix="$2"
+	  shift 2
+	  ;;
+      -p | --principalcomponents)
+	  PC="$2"
+	  shift 2
+	  ;;
+      -r | --ratiominimum)
+      	  RatioMinimum="$2"
+	  shift 2
+	  ;;
+      -w | --writeto) #write leafcutter clustering to this directory
+      	  OutputDirectory="$2"
+	  shift 2
+      	  ;;
+      -*) #unknown 
+	  echo "Error: Unknown option: $1" >&2
+	  exit 1
+	  ;;
+      *)  # No more options
+	  shift
+	  break
+	  ;;
+     esac
+done
+
+
+
 PATH=$PATH:"${LeafcutterLoc}"/scripts
+
+#should add a check for if a particular sample has already had junction files made for it and skip it
 
 if [ -d ~/test_runs/juncfiles ]
 then 
@@ -12,18 +65,15 @@ fi
 
 mkdir ~/test_runs/juncfiles # make a directory where the outputs will go - also update as an option
 
-cat fastq_list_star.txt | while read fastq #will make sure that the star outputs are the same as the leafcutter inputs
-do         
-	echo Converting "${fastq}" associated Aligned.out.bam to "${fastq}.starlaligned.junc"
-	sh $LeafcutterLoc/scripts/bam2junc.sh ~/test_runs/"${fastq}_star"/Aligned.out.bam ~/test_runs/juncfiles/"${fastq}.staraligned.junc"
-	echo "${fastq}.staraligned.junc" >> ~/test_runs/juncfiles/juncfiles.txt
+cat fastq_list_star.txt | while read line #iterate through the list
+do
+	Sample=$( echo "${line}" | cut -f 1 -d$'\t' )
+	echo Converting "${Sample}" associated Aligned.out.bam to "${Sample}.junc"
+	sh $LeafcutterLoc/scripts/bam2junc.sh ~/test_runs/"${Sample}_star"/Aligned.out.bam ~/test_runs/juncfiles/"${Sample}.junc"
+	echo "${Sample}.junc" >> ~/test_runs/juncfiles/juncfiles.txt
 done
-
 
 python "${LeafcutterLoc}"/clustering/leafcutter_cluster.py -j ~/test_runs/juncfiles/juncfiles.txt -m 50 -o "${out}" -l 500000
 zcat "${out}_perind.counts.gz" | grep "chr" > "${out}"_filtered_perind.counts.gz #filtering step - removes unmapped loci that woukld break leafcutter
-# add renameing step here
-#may be optional in future iterations
-/usr/local/bin/anaconda3/bin/python3 ~/scripts/counts_rename.py ~/test_runs/juncfiles/"${out}"_filtered_perind.counts.gz ~/E-GEUV-1.sdrf.txt ~/test_runs/juncfiles/
 #note this line requires full path
 /usr/local/bin/anaconda2/bin/python "${LeafcutterLoc}"/scripts/prepare_phenotype_table.py ~/test_runs/juncfiles/renamed_filt_perind.counts.gz -p 10
